### ISSUE TITLE
Зарядник боргов/модов ломает камеру, и не отпускает персонажа

### ISSUE THREAD

**Issue by VentelR** [ss220club/Paradise-SS220#1113]
### BYOND Version

515.1633

### Описание проблемы

При определенных действиях (в моем случае, я зашел в зарядник, во время сильных лагов) - камера блокируется на заряднике, в то время, персонаж свободно может перемещаться. При перезаходе - камера вновь центрируется на персонаже, однако зарядник всё еще считается занятым. Игрок может продолжать движение персонажем в любом направлении, однако, в тот момент, как кто то решит открыть зарядник - персонажа вернет в точку зарядника, где бы он не находился.
На скрине - мой персонаж, и злополучный зарядник.
![камера — копия](https://github.com/ss220club/Paradise-SS220/assets/87367109/7f5f61b2-5b19-4c0e-961b-34858a13b994)

### Что должно было произойти?

Зарядник не должен пожирать эфемерную меж пространственную копию персонажа, не должен ломать камеру.

### Шаги для повторения проблемы.

Зашел по диагонали в зарядник во время сильных лагов сервера. Ряд опрошенных игроков утверждает, что такое происходит и без лагов.

### Когда проблема началась?

Не хочу обманывать

**Comment by dj-34** [comment]
Древний баг с апстрима, думаю о нём и так знают
