### ISSUE TITLE
Ксено прически перекрывают возможность выбора другим расам

### ISSUE THREAD

**Issue by ARZUMATA** [ss220club/Paradise-SS220#1129]
### Описание проблемы

За человека невозможно выбрать некоторые причёски, например "Nia" в меню настройки персонажа.

### Что должно было произойти?

Некоторые прически должны быть в списке и доступны для выбора.

### Шаги для повторения проблемы.

Идем в настройки персонажа, где мы выбираем прическу, в появившемся TGUI выбираем нужную прическу.
![image](https://github.com/ss220club/Paradise-SS220/assets/54457203/d9f62fca-bb16-4141-b111-ed2a30b7fb9f)

### Когда проблема началась?

На оффах проблемы нет, скорее всего связанно с модульной системой, в дополнительной информации более детальное описание.

### Дополнительная информация

Я посмотрела, скорее всего проблема вот тут.
PR: https://github.com/ss220club/Paradise-SS220/pull/120

Инициализация GLOB.hair_styles_public_list идет верно:
![image](https://github.com/ss220club/Paradise-SS220/assets/54457203/c7a14bac-fb9f-4c64-a7ff-ff66a8e7bd3b)

А далее идет перекрытие и получаем "запрет" прически только для конкретной расы.
![image](https://github.com/ss220club/Paradise-SS220/assets/54457203/ca70057e-402b-4cdb-aec4-19cbcda33550)

Скорее всего из-за модуля идет обновление причесок в hair_styles_public_list, так как там привязка идет к ключу.
![image](https://github.com/ss220club/Paradise-SS220/assets/54457203/9bd9641d-39a0-4e17-92c5-8daed0574d3e)

Если сделать вот так:
![image](https://github.com/ss220club/Paradise-SS220/assets/54457203/293de7d5-1bc9-41be-b60f-a4fb5a1ea70b)

То мы получаем результат:
Nia - базовая, доступная всем 4-м расам как и должно быть.
![image](https://github.com/ss220club/Paradise-SS220/assets/54457203/0a421a00-6630-43f8-a44e-8495e8987a77)

Nia - для вульп из модуля, чисто для вульп.
![image](https://github.com/ss220club/Paradise-SS220/assets/54457203/df98f31a-c007-4ea8-a186-484c91b9039e)

В общем как я поняла, модуль перекрывает возможность выбора другим расам оставляя за собой лишь свою расу.

Из-за этого очень много причесок "выбывают" из меню выбора для людей, если под них созданы свои.

**Comment by larentoun** [comment]
Всё так и есть, можете сделать ПР, раз уже найдена причина? Просто пробежаться по всем модульным прическам, и где нужна определенная раса, просто в скобках добавить расу?

**Comment by ARZUMATA** [comment]
Там такая ситуация:
code\modules\mob\new_player\sprite_accessories\vulpkanin\vulpkanin_hair.dm

```
/datum/sprite_accessory/hair/vulpkanin
	icon = 'icons/mob/sprite_accessories/vulpkanin/vulpkanin_hair.dmi'
	species_allowed = list("Vulpkanin")
```

От него наследуются прически и если у "стандартных" и "новых", одинаковый "name", то последний имеет приоритет.
Поэтому добавить туда еще расовые разрешения наверно не очень правильно - модуль то для вульп был сделан. :)

Можно сделать другое имя скажем с префиксом, но на тех-же вульпах будет задвоение Nia и условной Nia-Vulp со спрайтами из разных .dmi (оффы и модуль)

Если я все правильно увидела, по большей части модуль дублирует основные прически и ломает возможность выбора последних.
modular_ss220\hairs\icons\vulpkanin_hair.dmi
icons\mob\sprite_accessories\human\human_hair.dmi

Плюс некоторые новые виды спрайтов для вульп вполне могут подойти и людям.
Например:
icon_state = "africanpigtails"
icon_state = "froofylong"

![image](https://github.com/ss220club/Paradise-SS220/assets/54457203/9e8f1a7d-11a6-4ebb-a133-cc704dfa255d)
![image](https://github.com/ss220club/Paradise-SS220/assets/54457203/e8217e8a-b2a6-4b35-a314-be4b67af92b6)

**Comment by larentoun** [comment]
Именно так и есть. А вульпы, разве, могут брать любые прически? Когда модуль вводили, у вульп был свой выбор причесок, потому так и вышло.

Вообще да, повторюсь, просто добавить в `name` вульпской версии приписку `(Vulpkanin)`.
