### ISSUE TITLE
РОБОТЕХИ - ЦЕНТР ДЮПА

### ISSUE THREAD

**Issue by BR54FF** [ss220club/Paradise-SS220#116]
**Issue Description**: ДЮП В АВТОЛАТЕ С ПОМОЩЬЮ МОДУЛЯ ДЛЯ УБОРОЧНОГО БОРГА (janitor cyborg floor buffer upgrade)

**What did you expect to happen**: Модуль должен корректно переработаться в автолате

**What happened instead**: Модуль выпал на пол, а металл всё равно прибавился

**Why is this bad/What are the consequences**: ДЮП

**Steps to reproduce the problem**: Если сделать улучшение для уборочного борга, а потом попробовать засунуть его в автолат, то металла в нём прибавится... А сам модуль упадёт на пол и можно будет дюпать дальше :ratgesus: 

**When did the problem start happening**: Была с самого зарождения

**Extra information**: Да.

**Comment by Furrior** [comment]
Ну, баним по р10 и делов то

**Comment by Gaxeer** [comment]
Вот и спалился, багоюзер. Теперь тебе отрубят руки

**Comment by larentoun** [comment]
Не ожидал от тебя...

**Comment by BR54FF** [comment]
ВЫ АФИГЕЛИ РАЗРАБЫ D:
