### ISSUE TITLE
Невозможность получить доступ к половине серверов через определённых провайдеров

### ISSUE THREAD

**Issue by ThaumicNik** [ss220club/Paradise-SS220#1167]
### Описание проблемы

У некоторых людей возникает проблема с подключением к серверам Green, Prime и Sierra. При подключении высвечивается ошибка "Connection failed after handshake". Вероятно, проблема связана с провайдерами. По словам @mell22, подобная проблема возникала с провайдером Билайн. У меня полностью аналогичная ей ситуация, но с провайдером Prolink.ru (локальная мелочь, найти информацию через кого они работают так и не смог). Проблема продолжается некоторое время и не исправляется путём стандартных операций, вроде перезагрузки оборудования или обращения в тех. поддержку провайдера. Адрес пингуется нормально, но не уверен, что данное IP соответствует актуальному.

![image](https://github.com/ss220club/Paradise-SS220/assets/69719123/26e66ed1-ffbe-4666-bf1a-1025966a7573)
![image](https://github.com/ss220club/Paradise-SS220/assets/69719123/970954e2-b142-440c-b67b-b6f90b52aeb9)
![image](https://github.com/ss220club/Paradise-SS220/assets/69719123/afb6b5a4-0694-48df-bb9e-e4bcb8b58441)

### Шаги для повторения проблемы.

Только если менять провайдера на одного из проблемных.

### Когда проблема началась?

Около 4-х суток назад. До этого встречалась у других людей.

### Дополнительная информация

Насколько мне известно, обойти проблему позволяет использование ВПН сервисов. Мне тоже удалось зайти при помощи их, но ввиду большой задержки, это вариант я вижу не валидным.

**Comment by dj-34** [comment]
Нерешаемо без прокладывания туннелей, или смены хостинг-провайдера.
