### ISSUE TITLE
Дюп шляп с помощью слизнекота

### ISSUE THREAD

**Issue by AyIong** [ss220club/Paradise-SS220#1170]
### Описание проблемы
Можно дюбать шляпы с помощью слизнекота, не критично, ибо кому нужны шляпы? Лол

### Шаги для повторения проблемы.
Надеть шляпу на слизнекота в хелп интенте

### Когда проблема началась?
Когда оффы портировали надевание шляп?

### Дополнительная информация
Думаю где-то что-то дублируется у слизнекота

**Comment by dj-34** [comment]
> Поглядел код, предполагаю что нужно над строчкой
> 
> https://github.com/ss220club/Paradise-SS220/blob/15f994d7d7d4a45eb8080f678d3250e53829ca53/modular_ss220/mobs/code/simple_animal/pets/slugcat.dm#L198
> 
> вставить код
> item_to_add.forceMove(src)
> Вечером только смогу проверить.

Было бы хорошо, если бы ты проверил и залил фикс
