### ISSUE TITLE
Проблема с чатом при трейторке

### ISSUE THREAD

**Issue by Silvirin** [ss220club/Paradise-SS220#1200]
### BYOND Version

515.1636

### Описание проблемы

Мне выпал мальф ИИ и сообщения в чате отображались не коректно. (каналы отделов в том числе общая рация) Станционные оповещения и ахелп работали как следует.
![изображение_2024-04-24_173254161](https://github.com/ss220club/Paradise-SS220/assets/168001041/4488bdbc-db25-4019-a9b0-76f102fe0d8b)

### Что должно было произойти?

Чат должен был отображаться коректно.

### Что случилось вместо этого?

Не вижу и не понимаю что говорят в чате.

### Почему это плохо/Какие последствия?

Я не понимаю что говорит экипаж а на слух определять трудно.

### Шаги для повторения проблемы.

Нажал реди в лобби.

### Когда проблема началась?

Как только запустился раунд и кто-то написал в чат.

**Comment by dj-34** [comment]
Дубликат https://github.com/ss220club/Paradise-SS220/issues/1133
