### ISSUE TITLE
TgUI (TgUI input) не принимает достаточно длинные строки.

### ISSUE THREAD

**Issue by msw7007** [ss220club/Paradise-SS220#1292]
### Описание проблемы

При вводе длинных строк при использовании tgUI если их размеры превышают опредленное (скорее всего внутреннее) заданое число символов в окне ввода, кнопка submit не отрабатывает (не происходит вызов процедур, окно не закрывается).
Данная проблема замечена в медицинских записях и при попытке импорта мелодий для музыкальных инструментов.

### Что должно было произойти?

Информация должна быть передана в процедуру на ее обработку.

### Что случилось вместо этого?

Ничего, окно не функционирует

### Почему это плохо/Какие последствия?

Нет возможности вводить длинные медицинские записи, что сказывается на РП. Нет возможности полноценного импорта мелодий в инструменты, что негативно сказывается на игровом опыте, который связан с музыкой.

### Шаги для повторения проблемы.

Взять строку длиной значительно более 1024 (почему так опишу позже). 
Взять в руки муз. инструмент. 
Нажать импорт
Вставить строку.
Нажать Submit

### Когда проблема началась?

Недели 2 назад импорт работал (не уверен, что он был через tgUI), обратил внимание на проблему примерно в районе 31-ого мая 2024

### Дополнительная информация

При нажатии на submit должна вызываться соответствующая функция. Тесты через VSC на примере проблемы импорта мелодий показали что при нажатии submit и длиной строки в районе 2к символов (привожу строку) не происходит вызова функции /datum/tgui_input_text/ui_act(action, list/params) из text_input.dm

При этом при вставке например текста в 500 символов вызов происходит.
Более точные тесту указали на длину в 1283 символа, если текст изначально представлен одной строкой (1283 символа отгружаются, 1284 нет) и 1243 если мультистрокой (полагаю, что это связано с тем, что используются символы переноса каретки на следующую строку).

Данная информация представлена в рамках форка билда при локальнйо установке.
На данный момент для игроков есть решение отключить tgUi Input (но он классный).

[Ноты Born to be Wild P1.txt](https://github.com/user-attachments/files/15612511/Born.to.be.Wild.P1.txt)

**Comment by dj-34** [comment]
Актуально?

**Comment by skifsky** [comment]
У оффов тг тоже есть такая проблема, похоже это связано с новыми версиями Бьенда https://github.com/tgstation/tgstation/issues/83722#issue-2334223259

**Comment by skifsky** [comment]
Проверил на локалке, видимо уже неакутально

**Comment by dj-34** [comment]
Видимо, не актуально.
