### ISSUE TITLE
У дрона нет возможности вставить батарейку в АПЦ

### ISSUE THREAD

**Issue by Kar4es** [ss220club/Paradise-SS220#1331]
### Описание проблемы

У дрона нет возможности вставить батарейку в АПЦ. Она просто выпадает из держателя при попытке поставить её в АПЦ.

### Что должно было произойти?

Ну вероятно батарейка должна быть вставлена в АПЦ

### Что случилось вместо этого?

хуй без соли

### Почему это плохо/Какие последствия?

дроны не стронг

### Шаги для повторения проблемы.

выше написано

### Когда проблема началась?

давненько

### Дополнительная информация

вероятно это надо на оффы

**Comment by dj-34** [comment]
Вроде должно быть пофикшено с вырезом модульного гриппера
