### ISSUE TITLE
Раунд начался, антажку дали а меня не впустило в раунд.

### ISSUE THREAD

**Issue by Zabanennbli** [ss220club/Paradise-SS220#1396]
### BYOND Version

515.1642

### Описание проблемы

Раунд начался, антажку дали а меня не впустило в раунд.

### Что должно было произойти?

Впустить в раунд)

### Что случилось вместо этого?

Не впустило)

### Почему это плохо/Какие последствия?

Потеря антажки)

### Шаги для повторения проблемы.

Без понятия. Стоял один капитан и готовность к антажным ролям. До этого меня кидало на рандомную роль всегда.

### Когда проблема началась?

Сегодня

### Дополнительная информация

![image](https://github.com/user-attachments/assets/e2a09906-84d9-4942-8bcc-ea111c64e851)

**Comment by dj-34** [comment]
Дубликат.
https://github.com/ss220club/Paradise-SS220/issues/1420
