### ISSUE TITLE
Не работает граната со слайм экстрактом

### ISSUE THREAD

**Issue by 4Aky** [ss220club/Paradise-SS220#1460]
### BYOND Version

515.1635

### Описание проблемы

Не срабатывает граната, собранная из экстракта слайма и молотой плазмы.

### Что должно было произойти?

Должен был быть эффект: пожар от гранаты с оранжевым экстрактом слайма или остановка времени от гранаты с экстрактом  сепии слайма. 

### Что случилось вместо этого?

Ничего

### Шаги для повторения проблемы.

Собирал гранату по такому методу: большой корпус гранаты + кабель + экстракт слайма (использовал два разных оранжевый или сепия) + 5 юнитов молотой плазмы в бикере + отвертка. 
Кидаешь и ничего не происходит, хотя сам механизм гранаты срабатывает. 

### Когда проблема началась?

Грин. Раунд: 9488, 2024-08-31 в 20-00

**Comment by dj-34** [comment]
Продублировано на оффы.
