### ISSUE TITLE
ББ и Трейтор из антагмикса не получают отложенные цели

### ISSUE THREAD

**Issue by m-dzianishchyts** [ss220club/Paradise-SS220#1509]
Братья по крови должны получать краткое описание целей и через 5-15 минут - точное, как с агентами.

**Comment by dj-34** [comment]
так по-моему все из антагмикса не получают отложенные цели

**Comment by dj-34** [comment]
Дубликат https://github.com/ss220club/Paradise-SS220/issues/1510
