### ISSUE TITLE
Накатить исправления рунчата

### ISSUE THREAD

**Issue by dj-34** [ss220club/Paradise-SS220#183]
https://github.com/ss220-space/Paradise/pull/2566

**Comment by Aylong220** [comment]
А зачем? Рунчат и так исчезает если закрыться в шкафу

**Comment by dj-34** [comment]
Нет рунчата в мехе, у боргов(вроде?). Не видно текста, когда кто-то говорит в шкафу

**Comment by Aylong220** [comment]
> Нет рунчата в мехе, у боргов(вроде?). Не видно текста, когда кто-то говорит в шкафу

Насчёт меха и боргов хз, должен быть.
А вот говорящий шкаф - нет
