### ISSUE TITLE
Убрать из ротации Мету и Цере

### ISSUE THREAD

**Issue by dj-34** [ss220club/Paradise-SS220#280]
Эти карты нами не поддерживаются, не имеют портанутых предметов, гейтов, на них не прилетают шаттлы синдиката и цк (админ шаттл)

**Comment by Furrior** [comment]
Все равно карта по голосованию. Думаю, забить на них просто и пусть игроки, если сильно хотят, выбирают карту, зная, что она такая себе

**Comment by dj-34** [comment]
> Все равно карта по голосованию. Думаю, забить на них просто и пусть игроки, если сильно хотят, выбирают карту, зная, что она такая себе

они не "такие себе" они сейчас без функциональных синдикатовец

**Comment by dj-34** [comment]
иметь их в ротации = убивать онлайн

**Comment by dj-34** [comment]
Сделано
