### ISSUE TITLE
Добавить звук при закрытии шкафа на замок

### ISSUE THREAD

**Issue by dj-34** [ss220club/Paradise-SS220#298]
Читай название

**Comment by Aylong220** [comment]
Найди звук закрытия и открытия замка xdd

**Comment by dj-34** [comment]
> Найди звук закрытия и открытия замка xdd

На РуПаре использовался deconstruct.ogg, если не ошибаюсь

**Comment by Aylong220** [comment]
Кринге, на оффах звуки везде пиздатые и свои

**Comment by dj-34** [comment]
> Кринге, на оффах звуки везде пиздатые и свои

он звучит вполне в тему

**Comment by Aylong220** [comment]
Он звучит как клик а не как закрытие-открытие замка
