### ISSUE TITLE
Изменить шрифт у эмоций и шепота, починить "Ё" (Рунчат)

### ISSUE THREAD

**Issue by dj-34** [ss220club/Paradise-SS220#313]
В данный момент на шепот накладывается italic, изза чего текст становится трудночитаем. У эмоций размер текста всратый, а буквы "Ё" отображается криво.

**Comment by dj-34** [comment]
Возможный фикс здесь
https://github.com/ParadiseSS13/Paradise/commit/9b7ec9a9802e1155478af27371333bd69113d809

**Comment by Aylong220** [comment]
Готово
