### ISSUE TITLE
Фамилии ЕРТ

### ISSUE THREAD

**Issue by LearIlGatto** [ss220club/Paradise-SS220#319]
Есть возможность выбирать ксенорасы для сотрудников ЕРТ, однако отсутствует возможность выбирать фамилии, соответствующие лору. Вместо этого ставятся стандартные людские фамилии, например, таяр Сергеев.

**Comment by Aylong220** [comment]
Вывод - запретить выбирать ксенорасы ЕРТшникам :Clueless:

**Comment by dj-34** [comment]
> Вывод - запретить выбирать ксенорасы ЕРТшникам :Clueless:

факт
