### ISSUE TITLE
Не заменён риг Shielded Hardsuit нюки с щитом на соответствующий мод с набором модулей.

### ISSUE THREAD

**Issue by LearIlGatto** [ss220club/Paradise-SS220#333]
Всё ещё старый риг, который лучше текущих модов из-за более удобных режимов и постоянно работающей брони.

**Comment by Aylong220** [comment]
Увы, ждём пока оффы дозаменяют риги на МОДы, у клоуна и мима тоже их нет

**Comment by LearIlGatto** [comment]
Понял, тогда ждём. там по идее и маг бутсы убирать надо, ибо с модами они не нужны особо.

**Comment by dj-34** [comment]
Решено апстримом
