### ISSUE TITLE
Шлюзы ЦК от подов заболтированы

### ISSUE THREAD

**Issue by LearIlGatto** [ss220club/Paradise-SS220#342]
В конце раунда по прилёту подов, шлюзы ЦК всё равно остаются заболтированными

**Comment by dj-34** [comment]
а у нас с этим ситуация крутая, либо ты болтируешь двери и не выпускаешь никого с цк в шлюзы (потому что они будут открыты раундстартом), либо болтируешь и они болтируются навсегда

**Comment by dj-34** [comment]
И тот вариант и другой - не лучший, можно пофиксить кодом, можно зарепортить оффам (им будет поебать я думаю). Но ситуация как есть 🤷‍♂️

**Comment by Aylong220** [comment]
Тут вроде я где-то насрал, и странно, вроде фиксил
Скорее всего тэг проебал

**Comment by dj-34** [comment]
@Aylong220 закрой
https://github.com/ss220club/Paradise-SS220/pull/370
