### ISSUE TITLE
В гейте blackmarketpackers можно застрять

### ISSUE THREAD

**Issue by dj-34** [ss220club/Paradise-SS220#344]
В гейте blackmarketpackers можно застрять, если "вылететь" за пределы гейта в космос.
Возможный фикс - добавление хелпера, блокирующего путь в 9-10 тайлов от края карты (его можно портировать с других билдов)
Возможно подобная проблема может присутствовать и на других гейтах с открытым космосом

**Comment by Aylong220** [comment]
Вроде пофиксили?
