### ISSUE TITLE
Терроры раундстартом

### ISSUE THREAD

**Issue by awkwardsocialist** [ss220club/Paradise-SS220#362]
Проблема не такая громкая как название :)

В гейте с пауками терроры вероятно выпадают людям из лобби. Либо у них самые быстрые руки на диком западе и они туда вошли из гостов в течении первых 30 секунд раунда. В любом случае так быть не должно
![what](https://github.com/ss220club/Paradise-SS220/assets/88992598/f3298772-a302-495f-b17b-8d77073ff6f5)

**Comment by Aylong220** [comment]
Знаю, хз пока как фиксить, плюс приболел
