### ISSUE TITLE
Диски и штука для дисков

### ISSUE THREAD

**Issue by awkwardsocialist** [ss220club/Paradise-SS220#368]
Нельзя нажать коробкой с дисками по штуке для дисков, чтобы они туда переместились. Вместо перемещения содержимого прокает перемещение коробки, которую машина "умно отвергает". Раньше это было возможно, так что буду признателен, если посмотрите почему так.

![blya](https://github.com/ss220club/Paradise-SS220/assets/88992598/f28956a5-0f38-4ced-84c4-611777ab783d)

**Comment by Aylong220** [comment]
На оффах этой фишки просто нет, посмотрим что можно сделать. Всё равно QoL

**Comment by Nlaysi** [comment]
вмержено на оффах, https://github.com/ParadiseSS13/Paradise/pull/22847

**Comment by Aylong220** [comment]
Найс
