### ISSUE TITLE
Дверь в гейте

### ISSUE THREAD

**Issue by awkwardsocialist** [ss220club/Paradise-SS220#369]
В новом гейте есть такая дверь, которой как мне сказали гейтеры не было. В общем посмотрите пожалуйста, что там, должна ли там быть иконка, сама дверь или это костыли. :)

![Безымянный](https://github.com/ss220club/Paradise-SS220/assets/88992598/a764be78-555b-4d02-beb9-bba9f16d17e9)

**Comment by konushi** [comment]
она невидима для некультистов, хотел оставить как фичу, а не баг
теперь буду исправлять

**Comment by konushi** [comment]
пофиксил
