### ISSUE TITLE
ТТС Tusk сбрасывается

### ISSUE THREAD

**Issue by Fullonibus** [ss220club/Paradise-SS220#380]
![image](https://github.com/ss220club/Paradise-SS220/assets/38350888/b77bad7d-c92d-468f-aa74-03054ce09ee1)

**Issue Description**: Когда стоит у куклы ттс Tusk при заходе в раунд сбивается на null

**What did you expect to happen**:  остается ттс Tusk

**What happened instead**: сбивается на null

**Why is this bad/What are the consequences**: человек второй раунд уже без голоса в раунде

**Steps to reproduce the problem**: установить Tusk в префах -> зайти в раунд -> обнаружить что немой

**When did the problem start happening**: при заходе в раунд

**Extra information**:

**Comment by dj-34** [comment]
Актуально?
