### ISSUE TITLE
Краш или белый/чёрный экран при подключении к серверу

### ISSUE THREAD

**Issue by ThaumicNik** [ss220club/Paradise-SS220#397]
При попытке войти на сервер (прайм и мейн) у некоторых игроков (включая меня) происходит один из нескольких сценариев:

* Клиент запускается, UI прогружается, но не реагирует на нажатия. Чат и меню действий пустые.
* Клиент запукается, UI прогружается, однако сразу же происходит выброс исключения с дальнейшим крашем.
* Клиент запускается и тут же крашится без ошибки.

Выяснить закономерность этих сценариев у меня не получилось. Все происходят случайно и у разных людей разные.

При этом зайти на любые другие сервера (вне системы SS220) успешно получается.

Стандартные процедуры, включая перезагрузку ПК, очистку кэша BYOND, очистку кэша IE, удаление IE, переустановку BYOND, переход на стабильную ветку BYOND и обратно, использование VPN, не помогают решить проблему. Проблема возникает даже на другом ПК (IP адрес тот-же).

Единственный актуальный и универсально работающий способ - переключение аккаунта на новый и игра на нём. Старый аккаунт у меня реанимировать так и не получилось. У некоторых игроков, впрочем, проблема самопроизвольно решалась через 10-15 переустановок BYOND, у меня, впрочем, как я писал ранее, это не сработало.

Смею предположить что проблема на стороне сервера. В #help в дискорде куча народу с такой же проблемой, и всем помогала именно смена аккаунта. 

Прилагаю пару скриншотов того, как это выглядит:
![image](https://github.com/ss220club/Paradise-SS220/assets/69719123/4ff3c672-1653-4f5e-9e13-acd13ca2b47d)
![image](https://github.com/ss220club/Paradise-SS220/assets/69719123/e2ba4b62-c3fb-43e4-8b66-56098c9f2ce7)

**Comment by dj-34** [comment]
возможно ли это из-за наличия не имеющихся на оффах рас, но занесенных у нас в БД? ;xmm:

**Comment by ThaumicNik** [comment]
Появилась гипотеза, что проблема в заглавных буквах в сикее.

**Comment by ThaumicNik** [comment]
Смена сикея не помогла как минимум одному человеку. WE ARE DOOMED

**Comment by dj-34** [comment]
Моё предположение - въебанная загрузка ресурсов

**Comment by Aylong220** [comment]
Давно не актуально
