### ISSUE TITLE
Cумка для растений SS14

### ISSUE THREAD

**Issue by BeaGHaoS** [ss220club/Paradise-SS220#413]
Cумка для растений у отдела гидропоники. Когда подбирается плод с растения либо же его семена, сумка каждый раз говорит что либо она заполнена либо то что предмет не подходит сумке. Это конечно не сильно критичный баг но порой надоедает постоянные уведомления. Заметил этот баг 12.10 около 21:20 по мск.

**Comment by dj-34** [comment]
Здесь только багрепорты по 13, тебе сюда
https://discord.com/channels/1097181193939730453/1108679943698780171
