### ISSUE TITLE
Кибериада: Мусор от священника и от библеря возвращается обратно

### ISSUE THREAD

**Issue by dj-34** [ss220club/Paradise-SS220#414]
Я думал это какой-то односессионный баг, но тут оказывается об этой проблеме заявили еще раз

**Comment by Kar4es** [comment]
> Я думал это какой-то односессионный баг, но тут оказывается об этой проблеме заявили еще раз

могу полностью систему просмотреть, косяки убрать

**Comment by Kar4es** [comment]
> Я думал это какой-то односессионный баг, но тут оказывается об этой проблеме заявили еще раз

если найду

**Comment by dj-34** [comment]
> > Я думал это какой-то односессионный баг, но тут оказывается об этой проблеме заявили еще раз
> 
> если найду

давай

**Comment by Kar4es** [comment]
https://github.com/ss220club/Paradise-SS220/pull/415

ждемс
