### ISSUE TITLE
[BOUNTY?] Титры

### ISSUE THREAD

**Issue by dj-34** [ss220club/Paradise-SS220#416]
Стримерский баунти (возможно) запрос - портировать титры с Инфинити
Манифест, рольки, антаги

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/df145955-5413-4721-ab3f-1925d42aa448)
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/9e6c11b4-52df-44f5-83c3-3a597465cf7b)

**Comment by Aylong220** [comment]
https://github.com/ss220club/Paradise-SS220/pull/424
