### ISSUE TITLE
Бэдтрип

### ISSUE THREAD

**Issue by dj-34** [ss220club/Paradise-SS220#421]
Накодить бэдтрип при передозе/случайно тяжелыми наркотиками

Референс
https://youtu.be/bSpYZSl76tY

**Comment by SadestMage** [comment]
А не проще прикрутить обычные галюны к этому?

**Comment by PhantornRU** [comment]
> А не проще прикрутить обычные галюны к этому?

Галюны-то ты прикрутишь, но бэдтрип накодить тоже нужно.
