### ISSUE TITLE
Улучшение света

### ISSUE THREAD

**Issue by dj-34** [ss220club/Paradise-SS220#422]
Closes https://github.com/ParadiseSS13/Paradise/pull/24534

Портировать
https://github.com/TauCetiStation/TauCetiClassic/pull/11943
https://github.com/TauCetiStation/TauCetiClassic/pull/12090

**Comment by DarthSidiousPalpatine** [comment]
Ой как неожиданно и приятно, и лестно)
Ну ничего, у нас скоро будет ещё одно обновление света, тоже потом портируете :P

RTX on SS13 comes true

**Comment by Aylong220** [comment]
Если доживём xdd

**Comment by dj-34** [comment]
> Если доживём xdd

Дожили

**Comment by DarthSidiousPalpatine** [comment]
А я помер на тау кеках. "Ещё одного обновления света" не случилось. Кеки всеми силами пытались отбить желание кодить и достигли успеха.
Живите долго и процветайте, парадизы. Тау Кекам соболезную.

**Comment by AyIong** [comment]
> А я помер на тау ките. "Ещё одного обновления света" не случилось. Киты всеми силами пытались отбить желание кодить и достигли успеха. Живите долго и процветайте, парадизы. Тау Кекам соболезную.

F

**Comment by MrRomainzZ** [comment]
@DarthSidiousPalpatine И ещё вопрос. Не твоих ли рук дело?
https://www.youtube.com/watch?v=Ovu_urtzCZE

**Comment by DarthSidiousPalpatine** [comment]
> @DarthSidiousPalpatine И ещё вопрос. Не твоих ли рук дело? https://www.youtube.com/watch?v=Ovu_urtzCZE

Да, мой старый видосик, тестил всякое. У меня был ещё видос где я зеркала делал прям, но не могу найти его.
![image](https://github.com/ss220club/Paradise-SS220/assets/21008918/393a5fbd-195e-46a9-bf65-8e8821acfcb3)
![image](https://github.com/ss220club/Paradise-SS220/assets/21008918/1b635da2-16a8-4a55-8ada-26c52f4e7d46)

А апдейт света должен был быть с heigh-map-ами, чтобы красиво свет ложился на объекты и пол, не однотонно:
![image](https://github.com/ss220club/Paradise-SS220/assets/21008918/2be1f61e-51f5-4608-afde-5e5cf4c98a3b)

Но Тау Кита решила пойти другим путём, туда им и дорога.

**Comment by MrRomainzZ** [comment]
> > @DarthSidiousPalpatine И ещё вопрос. Не твоих ли рук дело? [youtube.com/watch?v=Ovu_urtzCZE](https://www.youtube.com/watch?v=Ovu_urtzCZE)
> 
> Да, мой старый видосик, тестил всякое. У меня был ещё видос где я зеркала делал прям, но не могу найти его. ![image](https://private-user-images.githubusercontent.com/21008918/311721213-393a5fbd-195e-46a9-bf65-8e8821acfcb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjQ1MjcsIm5iZiI6MTcxMDE2NDIyNywicGF0aCI6Ii8yMTAwODkxOC8zMTE3MjEyMTMtMzkzYTVmYmQtMTk1ZS00NmE5LWJmNjUtOGU4ODIxYWNmY2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEzMzcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNTJmMTBjOTdlODhmMDZhMTQxOTJkYjU2ZTRiZmRlZTk0ZWI2YWYzYjllNzk5YzE2OWRmYmRkODUzNTMzZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lncwO0HJDnMM1ltjDQdVFFyxMTC7bC-TaAQgzd566qo) ![image](https://private-user-images.githubusercontent.com/21008918/311721230-1b635da2-16a8-4a55-8ada-26c52f4e7d46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjQ1MjcsIm5iZiI6MTcxMDE2NDIyNywicGF0aCI6Ii8yMTAwODkxOC8zMTE3MjEyMzAtMWI2MzVkYTItMTZhOC00YTU1LThhZGEtMjZjNTJmNGU3ZDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEzMzcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MGRjYjc3NmQ5NTY5M2I5YmZmMDFlNTFmNmI4ODM5NTBjZjU4YTI1YzFlNzEwMDBlYTJkYjZmZDMxNjA3MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.99nbrLGogKnsXzy9jDJj0oZbmw2BhK5tpL9GJAsrK8Y)
> 
> А апдейт света должен был быть с heigh-map-ами, чтобы красиво свет ложился на объекты и пол, не однотонно: ![image](https://private-user-images.githubusercontent.com/21008918/311721528-2be1f61e-51f5-4608-afde-5e5cf4c98a3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjQ1MjcsIm5iZiI6MTcxMDE2NDIyNywicGF0aCI6Ii8yMTAwODkxOC8zMTE3MjE1MjgtMmJlMWY2MWUtNTFmNS00NjA4LWFmZGUtNWU1Y2Y0Yzk4YTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEzMzcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NGJhNTFiZGYzODFlZjlmNzkxNzVkNGU2ZjU4MTA0NGFmZGYzMzEyZjM4M2RmZDA1MmQ4ZDdkNDY3ZTQzMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xe085QsAaJ54CGmjjrFHfyZTROUWvfMkd3VyY4lw44c)
> 
> Но Тау Кита решила пойти другим путём, туда им и дорога.

Выглядит просто невероятно... Надеюсь, у нас когда-нибудь получится достигнуть твоих успехов :)

**Comment by DarthSidiousPalpatine** [comment]
> Надеюсь, у нас когда-нибудь получится достигнуть твоих успехов :)

Я думаю ~~повторить судьбу Гаммы~~ сделать свой билд ~~с блекджеком и своими ПРами~~. Начну летом. Если будут успехи - может, портируете свет, будет красева.

**Comment by MrRomainzZ** [comment]
> Я думаю ~повторить судьбу Гаммы~ сделать свой билд ~с блекджеком и своими ПРами~. Начну летом. Если будут успехи - может, портируете свет, будет красева.

Очень ждём
