### ISSUE TITLE
Перевезти зоны карты 

### ISSUE THREAD

**Issue by Fullonibus** [ss220club/Paradise-SS220#427]
ТТС будет говорить зоны нормально, и при этом не возникнет вопросов "ЧТО ЭТО ЗА МЕСТО???" или возникнут? 🐀

**Comment by Aylong220** [comment]
Надо подумать как лучше это сделать 
Думаю в отдельном файле
Paradise-SS220\modular_ss220\maps220\code\Areas\translations.dm

**Comment by dj-34** [comment]
Возможно будет сложно реализуемо, потому что например зоны у контрактора берутся с названия зоны

**Comment by Aylong220** [comment]
Именно с названия а не с пути?

**Comment by dj-34** [comment]
> Именно с названия а не с пути?

именно с названия
