### ISSUE TITLE
Бармен с лавы. Доступы и внешность

### ISSUE THREAD

**Issue by Fullonibus** [ss220club/Paradise-SS220#428]
**Issue Description**:

У бармена с лавы нет доступов)) И внешность сгенерировалась веселая.
![image](https://github.com/ss220club/Paradise-SS220/assets/38350888/695d4d62-829c-47b4-9c02-7f337ddb7723)

**What did you expect to happen**: 

**What happened instead**:

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

**When did the problem start happening**:

**Extra information**:

**Comment by dj-34** [comment]
Ишуе можно закрыть, оффы вырезали(заменили) пляж на Лаваленде

**Comment by Fullonibus** [comment]
УВЫ
