### ISSUE TITLE
Иконка голода у генокрада

### ISSUE THREAD

**Issue by Fullonibus** [ss220club/Paradise-SS220#429]
**Issue Description**:

Когда генокрад превращается из вампира в другую куклу, у него остается иконка голода вампира (капля крови). В плане питания как обычная кукла.

**What did you expect to happen**: 

Иконка должна поменяться на бургер.

**What happened instead**:

Осталась капелькой крови.

**Why is this bad/What are the consequences**:

Может смутить игрока на генокраде, что он подумает что ему придется питаться кровью, хотя у него будет рацион текущей куклы.

**Steps to reproduce the problem**:

Превратиться в вампира, потом в другую куклу.

**When did the problem start happening**:

**Extra information**:

**Comment by larentoun** [comment]
Просьба продублировать на апстрим, проблема не с нашей стороны: https://github.com/ParadiseSS13/Paradise/issues
