### ISSUE TITLE
Частоты у СССП

### ISSUE THREAD

**Issue by Fullonibus** [ss220club/Paradise-SS220#445]
**Issue Description**:

![image](https://github.com/ss220club/Paradise-SS220/assets/38350888/78a2e280-23b8-4a40-a0d7-a53cf164f490)

Бойцы СССП любезно позаимствовали в свое пользование частоты дедсквада НТ. Явно работа советской разведки. Но было бы справедливо иметь советским солдатам и свою частоту вещания.

**What did you expect to happen**: 

СССП-шники общаются на своей частоте

**What happened instead**:

Они говорят на частоте дедсквада

**Why is this bad/What are the consequences**:

Не уверен что это прям настолько плохо, ибо эту частоту могут слышать только деды и офицеры ЦК.

**Comment by Aylong220** [comment]
До сих пор не пригодилось, вряд ли пригодится
