### ISSUE TITLE
ЕМП не работает на газовые маски СБ

### ISSUE THREAD

**Issue by LearIlGatto** [ss220club/Paradise-SS220#462]
После ЕМП можно передавать много информации о нападении на тебя через автоматические сообщения маски, что убивает стелс против СБ.
![изображение](https://github.com/ss220club/Paradise-SS220/assets/141523065/36ab6320-6ee2-4ddd-9bb6-205df9b100d5)

**Comment by mahdias0yaebaltvoumertvuymat** [comment]
Сделано для того, чтобы был хоть какой-то сигналл. Можно сменить "502 (Убийство)" на какое-нибудь менее вызывающее или вообще рандомное. Но чтобы место было
