### ISSUE TITLE
Не работает оверлей у неоновых кроссовок

### ISSUE THREAD

**Issue by dj-34** [ss220club/Paradise-SS220#470]
Не накладывается оверлей цвет у неоновых кроссовок (/obj/item/clothing/shoes/black/neon)

**Comment by Aylong220** [comment]
Шо, опять

**Comment by Aylong220** [comment]
Нет, просто код кривой

**Comment by dj-34** [comment]
> спрайты одежды из модуляра криво работают

спрайт одежды работает нормально, просто как сказал Эйлонг - кривой код

**Comment by Aylong220** [comment]
Потратил час на попытку починить - не вышло, понятия не имею как чинить эту хуйню. Оно даже на парашизе не работало Clueless

**Comment by dj-34** [comment]
> Потратил час на попытку починить - не вышло, понятия не имею как чинить эту хуйню. Оно даже на парашизе не работало Clueless

я тоже попробовал, хуй вышло. Не пойму как там оверлеи эти работают и хз где посмотреть примеры xdd

**Comment by Nlaysi** [comment]
Оверлей накладывается, но накладывается на иконку, а не на куклу. Вообще не уверен что можно накладывать оверлей на куклу

**Comment by Nlaysi** [comment]
Вроде на скайрате были подобные кроссовки, надо будет глянуть

**Comment by Aylong220** [comment]
Сомневаюсь что можно наложить оверлей на оверлей (коим и является шмотка)

**Comment by dj-34** [comment]
> Сомневаюсь что можно наложить оверлей на оверлей (коим и является шмотка)

Да можно, надо еще раз будет глянуть
