### ISSUE TITLE
Засчитывает цель, когда не должно

### ISSUE THREAD

**Issue by LearIlGatto** [ss220club/Paradise-SS220#485]
Засчитывает цель "Escape on the shuttle or an escape pod alive and free." выполненной, будучи связанным на основной части шаттла.

**Comment by dj-34** [comment]
Какая карта?

**Comment by dj-34** [comment]
"Основная часть шаттла" - это где?

**Comment by LearIlGatto** [comment]
Был в мед зоне шаттла отбытия, в слипере.
А разве не должна цель проваливаться, когда ты связанный? Потому что требование быть свободным есть

**Comment by dj-34** [comment]
> Был в мед зоне шаттла отбытия, в слипере. А разве не должна цель проваливаться, когда ты связанный? Потому что требование быть свободным есть

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/f6125d2e-957e-4495-bc03-ed8c1771c3f3)
Только если находится в СБ зоне

**Comment by dj-34** [comment]
Сразу уточню, что на шизах ровно такая же проверка на комплишен

**Comment by Aylong220** [comment]
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/944aeb83-8232-479b-97cd-469f61e072b4)
