### ISSUE TITLE
Баланс мейна

### ISSUE THREAD

**Issue by Aylong220** [ss220club/Paradise-SS220#508]
Спиздить спавнеры пушек с ТГ, и сделать на мейне старую оружейку, а на прайме текущую.
Засунуть вместо анаконды - пончик на мейн.
Убрать на мейне спидлоадеры к анаконде
Подрезать кобуры и перцовки везде

**Comment by BR54FF** [comment]
Щас закодим. jokerge

**Comment by dj-34** [comment]
Не актуально вроде?

**Comment by Aylong220** [comment]
пончик на месте, так шо похуй, спавнеры в долгом ящике
