### ISSUE TITLE
Нет ТТС при atom_say()

### ISSUE THREAD

**Issue by larentoun** [ss220club/Paradise-SS220#560]
Нужно добавить

**Comment by Aylong220** [comment]
Думаю если это добавить, серверу будет ещё хуже

**Comment by larentoun** [comment]
Надо тогда подумать, как предметам дать голос. Как же админом через водку говорить?

**Comment by dj-34** [comment]
> Надо тогда подумать, как предметам дать голос. Как же админом через водку говорить?

так пупс уже сделал

**Comment by dj-34** [comment]
или что?

**Comment by Aylong220** [comment]
Так сделал или что?
