### ISSUE TITLE
Feature: Дропподы

### ISSUE THREAD

**Issue by larentoun** [ss220club/Paradise-SS220#564]
Портировать дропподы с ТГ

**Comment by dj-34** [comment]
Это та самая хуйня с лутом из ниоткуда?...
даес фром кринж

**Comment by Gaxeer** [comment]
@dj-34 это для админабуза

**Comment by Aylong220** [comment]
Сику помер, будет ли это кто-то делать в будущем вообще?

**Comment by larentoun** [comment]
> Сику помер, будет ли это кто-то делать в будущем вообще?

Ультуй рессурект

**Comment by Aylong220** [comment]
ПКМ -  Rejuvinate

**Comment by dj-34** [comment]
Не думаю что кто-то будет это кодить
