### ISSUE TITLE
Feature: техфабы в отделы + сило

### ISSUE THREAD

**Issue by larentoun** [ss220club/Paradise-SS220#565]
Опять же, портируем с ТГ

**Comment by Aylong220** [comment]
Сило? Надеюсь все это на оффы gatto

**Comment by larentoun** [comment]
Просто намаппим на наши мапы clueless

**Comment by Aylong220** [comment]
И это тоже... сику помер и вряд ли кто-то будет делать

**Comment by larentoun** [comment]
> И это тоже... сику помер и вряд ли кто-то будет делать

Если вообще нужда имеется?

**Comment by Aylong220** [comment]
Для щитспавна было бы неплохо, наверное

**Comment by Aylong220** [comment]
Кхм, ничего не было
Наверное нужды нет, по крайней мере не в ближайшем будущем
