### ISSUE TITLE
Выделение осмотра

### ISSUE THREAD

**Issue by dj-34** [ss220club/Paradise-SS220#74]
На нашей Паре осмотр был выделен в окошко, а не в
*---*
хуй
*---*
и прочее

(офф пара)
![image](https://github.com/ss220club/Paradise-Remake/assets/20109643/3d244831-04a9-49c4-9197-7fbfa9a6e26b)
![image](https://github.com/ss220club/Paradise-Remake/assets/20109643/6c5a9af6-71de-4a5e-8aa7-cbb6c08d8ea1)

**Comment by Aylong220** [comment]
Делают оффы
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/ce96f403-1dbe-4515-aa1b-7bc7aa73bb08)
