### ISSUE TITLE
Вернуть Тенелингов

### ISSUE THREAD

**Issue by dj-34** [ss220club/Paradise-SS220#88]
Ну они же были крутые... тимап, хайвмайнд, темнота и порабощение, всё-такое...
https://github.com/ParadiseSS13/Paradise/pull/17467

**Comment by Aylong220** [comment]
Увы

**Comment by dj-34** [comment]
> Увы

непон? схуяли

**Comment by Aylong220** [comment]
Кто-то собирается в ближайшее время их портировать?

**Comment by dj-34** [comment]
> Кто-то собирается в ближайшее время их портировать?

в ближайшее - не ебу, если никто не возьмется, то я буду траить в будущем

**Comment by Aylong220** [comment]
Ну удачи xdd

**Comment by ErdGinalD** [comment]
> Ну они же были крутые... тимап, хайвмайнд, темнота и порабощение, всё-такое... [ParadiseSS13#17467](https://github.com/ParadiseSS13/Paradise/pull/17467)

так хуйня из под коня же, асистухи с станпродом обмазанные гуталином.

**Comment by Aylong220** [comment]
Ну чё там, диджей?

**Comment by dj-34** [comment]
> Ну чё там, диджей?

ну висит и висит, че тут говорить. Может однажды
